### PR TITLE
Readonly Addons Folder, addons-linter via API

### LINKED ISSUE #35: Integrate add-ons linter in assay
Currently our code manager shows inline lint offences like potential unsafe DOM injections etc when browsing add-on code. 

We should migrate this feature to Assay to help reviewers with visual cues to interesting parts of the source code.

Ref: https://github.com/mozilla/addons-linter/

### PR DESCRIPTION
**Pull request by chrstinalin**
Closes #35 

**Changes**
- The root folder is set as readonly in VS Code using the settings property [`files.readonlyInclude`](https://code.visualstudio.com/updates/v1_79#_readonly-mode), making use of Glob patterns to do so.
- Whenever the root folder is changed in settings, the readonly property is removed from the initial root folder and added to the new one.
- Assay will forcibly set the root folder as readonly again if the user attempts to remove the root folder from `files.readonlyInclude`.

**Note 1**: This isn't the ideal way of going about it and is a bit hack-y, but the alternative `TextDocumentContentProvider` would introduce more problems (which handles individual files -- to have it working with the file explorer would mean listening for a text editor open, immediately closing that editor, and opening the readonly document instead -- which one can imagine could be an unpleasant user experience.)

**Note 2**: The readonly state prevents the user from deleting or modifying anything in the root folder within VS Code. However, as of now, there's no failsafe for when a user modifies the add-on code externally (ex. in a text editor). There's a lot of different options here (such as checking the 'last modified' state of add-ons), but the computational work to check every time may not be worth it. Best to discuss this over Zoom.

image
image
- `reviewUrls.cache` -> `addonMeta.cache `to additionally store the xpi's file id under its version and addon id (as the validation endpoint does not take GUID nor version)
- Lints are fetched from the API endpoint [`/reviewers/addon/<addon_id>/file/<file_id>/validation/`](https://github.com/diox/olympia/blob/9eaed4d5924ec9e9ef180ef3579c38004269d392/docs/topics/api/reviewers.rst) on launch iff the user's workspace is opened to a version.

image

Also of note is a [separate repository for a standalone addons-linter extension](https://github.com/chrstinalin/vscode-addons-linter), when/if we want to go down that route.

### CODE REVIEW

**Comment by chrstinalin** [comment]
Note: #62 was pushed on request and included a refactored version of the code introduced in this branch.

**Comment by willdurand** [comment]
@chrstinalin what is the status of this PR now?

**Comment by chrstinalin** [comment]
> @chrstinalin what is the status of this PR now?

Brought it up with Simeon yesterday who said just to close it since it was merged as part of the refactor.

**Comment by chrstinalin** [comment]
Refactored version merged as part of #62

**Pull request closed without merging**
